#!/bin/sh
x86_64-apple-darwin9-install_name_tool \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libgdiplus.0.dylib     @loader_path/libgdiplus.0.dylib      \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libglib-2.0.0.dylib    @loader_path/libglib-2.0.0.dylib     \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libintl.8.dylib        @loader_path/libintl.8.dylib         \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libcairo.2.dylib       @loader_path/libcairo.2.dylib        \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libpixman-1.0.dylib    @loader_path/libpixman-1.0.dylib     \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libtiff.5.dylib        @loader_path/libtiff.5.dylib         \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libjpeg.8.dylib        @loader_path/libjpeg.8.dylib         \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libgif.4.1.6.dylib     @loader_path/libgif.4.1.6.dylib      \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libfontconfig.1.dylib  @loader_path/libfontconfig.1.dylib   \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libfreetype.6.dylib    @loader_path/libfreetype.6.dylib     \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libpng14.14.dylib      @loader_path/libpng14.14.dylib       \
-change /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/libexpat.1.6.7.dylib   @loader_path/libexpat.1.6.7.dylib    \
$1
